version: '3.8'
name: quyen-compose
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "33067:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin@ADMIN
    volumes:
      - ezio-postgres-java-data:/var/lib/postgres
    networks:
        - java-app

  spring-boot-app:
    container_name: ezio-spring
    image: ezioquyen/testsql-spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin@ADMIN
    depends_on:
        - postgres
    networks:
      - java-app

volumes:
  ezio-postgres-java-data:
networks:
  java-app:
    name: java-app