version: '3.8'
name: quyen-compose
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "33067:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin@ADMIN
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:33067" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - ezio-postgres-java-data:/var/lib/postgres
    networks:
        - java-app

  spring-boot-app:
    container_name: ezio-spring
      context:.
    image: ezioquyen/testsql-spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin@ADMIN
    depends_on:
        postgres:
          condition: service_healthy
    networks:
      - java-app

volumes:
  ezio-postgres-java-data:
networks:
  java-app:
    name: java-app