version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - "33067:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin@ADMIN

  spring-boot-app:

    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin@ADMIN
    depends_on:
      - postgres
